# - name: Get existing firewall config
#   ansible.builtin.command: uci show firewall
#   register: firewall_config
#   changed_when: false

# - name: Ensure port forward rules
#   ansible.builtin.shell: |
#     uci add firewall redirect
#     uci set firewall.@redirect[-1].name='{{ item.name }}'
#     uci set firewall.@redirect[-1].src='wan'
#     uci set firewall.@redirect[-1].src_dport='{{ item.src_port }}'
#     uci set firewall.@redirect[-1].dest='lan'
#     uci set firewall.@redirect[-1].dest_ip='{{ item.dest_ip }}'
#     uci set firewall.@redirect[-1].dest_port='{{ item.dest_port }}'
#     uci set firewall.@redirect[-1].proto='tcp'
#     uci commit firewall
#   when: "'name={{ item.name }}' not in firewall_config.stdout"
#   notify: Restart firewall
#   loop: "{{ forwarding_ports }}"