---
# tasks file for ansible-role-wireguard-installation-openwrt
- name: Install WireGuard packages
  community.general.opkg:
    name:
      - kmod-wireguard
      - wireguard-tools
      - luci-proto-wireguard
      - rpcd-mod-wireguard
    state: present
    update_cache: yes

- include_tasks: generate_keys.yml
- include_tasks: setup_interface.yml
- include_tasks: setup_firewall.yml
- include_tasks: forwarding_ports.yml

- name: Disable Allow-Admin rule
  ansible.builtin.command: uci set firewall.breach.enabled='0'
  when: block_wan_access


