
# Zone configuration for WireGuard interface
- name: Setting up Firewall | Ensure wg zone exists
  command: uci set firewall.wg_zone=zone

- name: Setting up Firewall | Set zone name
  command: uci set firewall.@zone[-1].name='wg'

- name: Setting up Firewall | Attach network
  command: uci set firewall.@zone[-1].network='{{ wg_server_interface }}'

- name: Setting up Firewall | Set input policy
  command: uci set firewall.@zone[-1].input='ACCEPT'

- name: Setting up Firewall | Set output policy
  command: uci set firewall.@zone[-1].output='ACCEPT'

- name: Setting up Firewall | Set forward policy
  command: uci set firewall.@zone[-1].forward='ACCEPT'
  notify: 
    - Apply firewall
    - Restart firewall


# Forwarding configuration
- name: Setting up Firewall | Add forwarding section
  command: uci set firewall.wg_lan_forward=forwarding

- name: Setting up Firewall | Set forwarding source
  command: uci set firewall.wg_lan_forward.src='wg'

- name: Setting up Firewall | Set forwarding destination
  command: uci set firewall.wg_lan_forward.dest='lan'

- name: Setting up Firewall | Add forwarding section
  command: uci set firewall.wg_wan_forward=forwarding

- name: Setting up Firewall | Set forwarding source
  command: uci set firewall.wg_wan_forward.src='wg'

- name: Setting up Firewall | Set forwarding destination
  command: uci set firewall.wg_wan_forward.dest='wan'
  notify: 
    - Apply firewall
    - Restart firewall


- name: Setting up Firewall | Add firewall rule section
  command: uci set firewall.wg_wan_rule=rule

- name: Setting up Firewall | Set rule name
  command: uci set firewall.wg_wan_rule.name='Allow-WireGuard'

- name: Setting up Firewall | Set rule source
  command: uci set firewall.wg_wan_rule.src='wan'

- name: Setting up Firewall | Set destination port
  command: uci set firewall.wg_wan_rule.dest_port='{{ wg_server_port }}'

- name: Setting up Firewall | Set protocol
  command: uci set firewall.wg_wan_rule.proto='udp'

- name: Setting up Firewall | Set target
  command: uci set firewall.wg_wan_rule.target='ACCEPT'
  notify: 
    - Apply firewall
    - Restart firewall



# NAT setup
- name: Setting up Firewall | Add firewall nat section
  command: uci set firewall.wg_nat=nat

- name: Setting up Firewall | Set section name
  command: uci set firewall.wg_nat.name='WireGuard-NAT'

- name: Setting up Firewall | Set source interface
  command: uci set firewall.wg_nat.src='wg'

- name: Setting up Firewall | Set masquerade
  command: uci set firewall.wg_nat.target='MASQUERADE'
  notify: 
    - Apply firewall
    - Restart firewall

