---
# handlers file for ansible-role-wireguard-installation-openwrt
- name: Restart network
  service:
    name: network
    state: restarted

- name: Restart firewall
  service:
    name: firewall
    state: restarted
