---
# handlers file for ansible-role-wireguard-installation-openwrt
- name: Restart network
  service:
    name: network
    state: restarted

- name: Apply network
  command: uci commit network

- name: Restart firewall
  service:
    name: firewall
    state: restarted

- name: Apply firewall
  command: uci commit firewall
